version: '3'
services:
  easy-bill-mysql:
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    restart: always
    container_name: easy-bill-mysql
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
  easy-bill:
    build: docker
    environment:
      # 测试
      EASY_BILL_TG_TOKEN: 1234567890:ABCD-1234abcdefghijklmnopqrstuvwxyz
      EASY_BILL_MYSQL_DSN: root:my-secret-pw@tcp(easy-bill-mysql:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
    container_name: easy-bill
    depends_on:
      - easy-bill-mysql
    restart: always



